name: Test Deployed API

on:
  push:
    branches: ["main"]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Test /health endpoint
        run: |
          echo "Checking health API..."
          response=$(curl -s https://portfolio-backend-hzbj.onrender.com/health)
          echo "Response: $response"
          echo $response | grep "ok"

      - name: Test /leaderboard endpoint
        run: |
          echo "Checking leaderboard API..."
          response=$(curl -s https://portfolio-backend-hzbj.onrender.com/leaderboard)
          echo "Response: $response"
          echo $response | grep "leaderboard"
