name: Deploy & Verify

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy
        run: |
          echo "🚀 Triggering deployment..."
          curl -s -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

      - name: Wait for Deployment to be Ready
        run: |
          echo "⏳ Waiting for deployment to become healthy..."

          MAX_ATTEMPTS=15
          INTERVAL=10

           for ((i=1;i<=MAX_ATTEMPTS;i++)); do
            status=$(curl -s -o /dev/null -w "%{http_code}" https://portfolio-backend-hzbj.onrender.com/health)

            echo "Attempt $i/$MAX_ATTEMPTS → Status: $status"

            if [ "$status" -eq 200 ]; then
              echo "✅ Deployment successful!"
              exit 0
            fi

            echo "Still not ready, retrying in $INTERVAL seconds..."
            sleep $INTERVAL
          done

          echo "❌ Deployment failed after $MAX_ATTEMPTS attempts"
          exit 1
